---
abstract: 'a framework for building data service applications for the Web'
author:
  - 'Michael McClennen <mmcclenn@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-DataService
provides:
  Web::DataService:
    file: lib/Web/DataService.pm
    version: 0.11
  Web::DataService::PodParser:
    file: lib/Web/DataService/PodParser.pm
  Web::DataService::Request:
    file: lib/Web/DataService/Request.pm
requires:
  Dancer: 0
  HTTP::Validate: 0.35
  Try::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
